version: '3.4'

services:
  tailadminvuefree:
    image: tailadminvuefree
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
